### ISSUE TITLE
Mackerel Users Group Meeting Vol.1

### ISSUE THREAD

**Issue by karupanerura** [mackerel-ug/event#1]
- [x] 日程と会場を決定する - 6/14(火) at エウレカ
- [x] イベントの名前を決める - Mackerel Users Group Meeting
- [x] イベントのコンセプトを決める - Mackerelと私
  - ゆるふわ感あるとよさそう
- [x] 今回のテーマを決める - Mackerelをサーバ監視/管理"以外"に使う
- [x] イベントのタイムテーブルを切る - LTx8
- [x] イベント参加登録に使うサイトを選定 - connpass
- [x] イベント参加登録が可能な状態にする - http://mackerel-ug.connpass.com/event/33287/
- [x] 開催告知記事を作成する
- [x] 開催告知を行う
- [x] （1周間前）リマインドを行う
- [x] （当日朝/夕）リマインドを行う
- [x] （受付まで）参加者リストを用意し印刷する
- [x] （受付終了後）懇親会会場の席を確保する

**Comment by karupanerura** [comment]
タスク適当に切りました

**Comment by karupanerura** [comment]
名前はMackerel Users Group Meetingにしようかと思います。ご意見あればお気軽にどうぞ。

**Comment by yokoninaritai** [comment]
会場は問題なければエウレカ使いませんか？

**Comment by karupanerura** [comment]
ではお借りできればと思います！

**Comment by karupanerura** [comment]
6/14(火)に決定

**Comment by karupanerura** [comment]
イベントのコンセプトですが「Mackerelと私」でどうでしょうか。

**Comment by karupanerura** [comment]
あとは、イベントのタイムテーブルを切れば公開できそう。
初回だし、LT大会みたいな感じでLT8本とかでどうでしょうか。

**Comment by papix** [comment]
一応User Groupの1回目ですし, もう1回｢Mackerel User Group作ります!｣或いは｢Mackerel User Groupやっていくぞ!｣みたいな話をやってもいいかな, と思いました.

LT8本というタイムテーブル, 良いと思います! いろいろ企画頂いて, ありがとうございます!

**Comment by karupanerura** [comment]
ありがとうございます。よさげということで今日中にイベントページの叩きをあげられるといいかなと思います。
イベントサイトはconnpassあたりでいいですかねー。

**Comment by karupanerura** [comment]
@papix: @buty4649 @yokoninaritai 
遅くなりました。タイムテーブル、ご確認ください。
http://mackerel-ug.connpass.com/event/33287/preview/

**Comment by karupanerura** [comment]
確認事項
- [x] キャパシティ: 50人で設定しているがOKか
- [x] 懇親会: 立地的に会場内でケータリングが良さそうだがどうか（近くに良い居酒屋あればそこでも）
- [x] LT: LTでMackerel User Group自体の話を入れてはどうか

**Comment by yokoninaritai** [comment]
近くに和民ならあります。

**Comment by karupanerura** [comment]
したら和民でもよさそうですね

**Comment by yokoninaritai** [comment]
会場としては一応100くらいまで入りますが100入れると結構いっぱいになるので最大80くらいがいいかもしれません。

**Comment by karupanerura** [comment]
問題なければ月曜には公開しますよ

**Comment by papix** [comment]
Connpass確認しました! タイムテーブル含めてOKと思います!
月曜日の朝〜昼辺りに, ドーンと公開しちゃいましょう!

**Comment by karupanerura** [comment]
公開ed http://mackerel-ug.connpass.com/event/33287/

**Comment by karupanerura** [comment]
終わってるので閉じるよ
