### ISSUE TITLE
Mackerel Users Group Meeting Vol.2 in Osaka

### ISSUE THREAD

**Issue by papix** [mackerel-ug/event#2]
- [x] 日程を決定する ... 9月20日(火)
- [x] 会場を決定する ... エムオーテックス株式会社さま 10Fカフェスペース
- [x] イベント名を決定する ... Mackerel Users Group Meeting Vol.2 in Osaka
- [x] コンセプトを決める ... Mackerelと私 (前回と同じ)
- [x] テーマを決める ... ｢はじめましてMackerel, はじめましてAWS integration｣
- [x] タイムテーブルを切る
- [x] イベント参加が可能な状態にする(Connpass)
  - http://mackerel-ug.connpass.com/event/39133/
- [ ] 開催告知記事を作る
- [ ] 開催告知をする
- [ ] リマインドする(1週間前)
- [ ] リマインドする(当日)
- [ ] 参加者リストを準備する

**Comment by papix** [comment]
#1 を参考にしてタスクを切りました.

**Comment by papix** [comment]
今回は始めての関西圏(大阪)での開催です. 会場はほぼ確定しています(細かい調整中).

**Comment by papix** [comment]
イベント名は｢Mackerel Users Group Meeting Vol.2 in Osaka｣にしたいと思います.
あとは, コンセプトとテーマですね. 前回はコンセプトが｢Mackerelと私｣, テーマが｢Mackerelをサーバ監視/管理"以外"に使う｣でした. 今回はどうしましょう...

**Comment by papix** [comment]
会場は, 新大阪の｢エムオーテックス株式会社｣さまの10Fカフェスペースをお借り出来ることになりました!

**Comment by papix** [comment]
｢コンセプト｣は, 前回から引き続き｢Mackerelと私｣で.

**Comment by papix** [comment]
｢テーマ｣は, ｢はじめましてMackerel, はじめましてAWS integration｣で.

Mackerelを始めてみました, というお話や, AWS integration試してみた! というお話などがあればいいな, という意図です!

**Comment by papix** [comment]
# タイムテーブル
- 19:00 ... 開場
- 19:30〜19:40 ... アナウンス(開場説明, 懇親会の案内など)
- 19:40〜19:45 ... Mackerel User Groupについて
- 19:45〜19:50 ... LTその1
- 19:50〜19:55 ... LTその2
- 19:55〜20:00 ... LTその3
- 20:00〜20:10 ... 休憩
- 20:10〜20:15 ... LTその4
- 20:15〜20:20 ... LTその5
- 20:20〜20:25 ... LTその6
- 20:25〜20:30 ... LTその7
- 20:30〜22:00? ... 懇親会(希望者のみ)

**Comment by papix** [comment]
Connpassでイベント立てました: http://mackerel-ug.connpass.com/event/39133/

**Comment by karupanerura** [comment]
台風でFAIL
