### ISSUE TITLE
Mackerel Users Group Meeting Vol.3

### ISSUE THREAD

**Issue by karupanerura** [mackerel-ug/event#3]
- [x] 日程と会場を決定する - 8/23(水) キャンプファイヤー
  - 18:00-22:00 押さえて貰っている
- [x] 今回のテーマを決める - XaaS meets Mackerel
- [x] イベントのタイムテーブルを切る - LTx8
- [x] タイムテーブルを切る
- [x] イベント参加が可能な状態にする(Connpass)
- [ ] 開催告知記事を作成する
- [ ] 開催告知を行う
- [x] （1周間前）リマインドを行う
- [x] （3日前）懇親会予算を確定して発注準備を行う(何をどれくらい発注するか確定させる/配達時刻も確認する)
- [x] （当日朝）予め決めてあった数で発注する
- [x] （当日朝/夕）リマインドを行う
- [ ] （受付まで）参加者リストを用意し印刷する

**Comment by yokoninaritai** [comment]
会場ですが、campfireのオフィスはつてがあるので借りれると思います。DMMも確認が必要ですが可能かと思います。

**Comment by karupanerura** [comment]
ありがとうございます！ 
そういえばキャパシティも決めなければ。

**Comment by karupanerura** [comment]
1年ほど時間があいていますが、第一回が外苑前で45人、第二回が新大阪で10人。
公式のMackerel Meetupは最近は70人前後の参加ということを考えても、少なくとも50人〜60人のキャパシティは必要そうです。

**Comment by karupanerura** [comment]
@yokoninaritai 少なくとも50人〜60人のキャパシティが必要と考えたときにcampfireさんとDMMさんではいけそうか確認してもらえますでしょうか。
campfireだとぼくも中のひとにつてがあるのでcampfireさんにまずは確認してもらえるとうれしいです。
そして、できればmackerel導入している会社さんだといいきがしています。（導入状況をしらない）

**Comment by yokoninaritai** [comment]
@karupanerura 返事遅くなってすみません。確認しておきます。

**Comment by yokoninaritai** [comment]
campfireの方は100人くらいは入るって事でした。
mackerelはあまり活用はできてませんが使っているって聞いてます。
guest用のwifi もありました。
日程がfixしたら調整します。

DMMの方は現在確認中です。

**Comment by karupanerura** [comment]
ありがとうございます。campfireさんはキャパシティは十分そうですね。
日程にかんしては会場の空き状況に完全に左右されちゃうので、8月中頃 OR 9月中頃 でいまのところどこの日程で会場となる部屋が空いているかご確認頂けますとありがたいです 🙏

**Comment by yokoninaritai** [comment]
今のところは空いてそうでした。

**Comment by karupanerura** [comment]
8月中頃 OR 9月中頃 では(いまのところは)空いてない日程はないという認識でよいでしょうか

**Comment by yokoninaritai** [comment]
8月中頃 or 9月中頃  の全日程ですでに埋まっている日を再度確認してます。もう少しお待ちください。

**Comment by yokoninaritai** [comment]
キャンプファイヤーのスペースですが、下記の日程は埋まっているようでした。
```
8/5(土)
8/9(水)
8/31(木)
9/2(土)
9/20(水)
9/26(火)
9/27(水)
```

**Comment by karupanerura** [comment]
ありがとうございます！

この日程で相談してみて頂けると良いかなと思いますがご都合どうでしょうか。（他のイベントの日程と会場の空きと自分のスケジュールを加味して適当に案を決めました）
第一候補: 8/25(金)
第二候補: 9/15(金)
第三候補: 8/18(金) （この日は自分が行けるかあやしい…）

重複イベントがないかはこのへんで一応調べましたがいまのところはなさそうでした。
https://techplay.jp/calendar?ym=2017-08
https://techplay.jp/calendar?ym=2017-09

**Comment by karupanerura** [comment]
@yokoninaritai この日程のどちらか抑えて貰えるようお願いして頂いてもいいですか:
* 第一候補: 8/25(金)
* 第二候補: 9/15(金)

**Comment by yokoninaritai** [comment]
@karupanerura 金曜日がキャンプファイヤーの全体定例があるそうで、20時開始になりそうなんですがいいでしょうか？

**Comment by karupanerura** [comment]
おっと！厳しそうですね。20時開始というのは、会場が貸せる時間がということかと思うので、会場準備の時間込みになりますよね…？
仮に20時から受付開始できるにしても20:30からとかになりそうでちょっと夜遅くなってしまってつらそうですね…。それでは金曜日は避けましょう。

- 8/23(水)
- 9/6(水)

こちらだと如何でしょうか

**Comment by yokoninaritai** [comment]
確認します。

**Comment by karupanerura** [comment]
🙏

**Comment by yokoninaritai** [comment]
どちらも大丈夫そうです。
一旦8/23 押さえてもらうように連絡しますがいいですか？
時間は18時くらいからでいいですか？

**Comment by karupanerura** [comment]
ありがとうございます！では8/23を18時くらいから押さえてもらいましょう（実際のイベント開始は19時か19時半くらいにするかとおもいますが

**Comment by yokoninaritai** [comment]
8/23 18時 〜 22時で押さえてもらってます。
飲食についても問題ないです。
会場提供だけなので、飲食物の用意は必要です。

**Comment by karupanerura** [comment]
ありがとうございます！じゃあ会場で懇親会もやる方向で検討進めます

**Comment by karupanerura** [comment]
connpass作った: https://mackerel-ug.connpass.com/event/62553/preview/

**Comment by karupanerura** [comment]
タイムテーブルこんな感じでどうでしょう
![image](https://user-images.githubusercontent.com/374550/28331936-e920a730-6c2d-11e7-9fc6-3d7b80551231.png)
source: https://github.com/mackerel-ug/Mother/blob/mackerel-ug/config/event.yaml

**Comment by karupanerura** [comment]
公開した: https://mackerel-ug.connpass.com/event/62553/
